// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.4
// source: wishlist.proto

package hipstershop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// demo.proto already defines an Empty message in this package, so the wishlist
// service brings its own name to avoid a collision when both files are
// generated into the same Go package (as they are in the frontend).
type WishlistEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WishlistEmpty) Reset() {
	*x = WishlistEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WishlistEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishlistEmpty) ProtoMessage() {}

func (x *WishlistEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishlistEmpty.ProtoReflect.Descriptor instead.
func (*WishlistEmpty) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{0}
}

type WishlistItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	AddedAt   int64  `protobuf:"varint,2,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"` // unix seconds
}

func (x *WishlistItem) Reset() {
	*x = WishlistItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WishlistItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishlistItem) ProtoMessage() {}

func (x *WishlistItem) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishlistItem.ProtoReflect.Descriptor instead.
func (*WishlistItem) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{1}
}

func (x *WishlistItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *WishlistItem) GetAddedAt() int64 {
	if x != nil {
		return x.AddedAt
	}
	return 0
}

type Wishlist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt int64           `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	ItemCount int32           `protobuf:"varint,4,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	Items     []*WishlistItem `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"` // only populated by GetWishlist
}

func (x *Wishlist) Reset() {
	*x = Wishlist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wishlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wishlist) ProtoMessage() {}

func (x *Wishlist) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wishlist.ProtoReflect.Descriptor instead.
func (*Wishlist) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{2}
}

func (x *Wishlist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wishlist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wishlist) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Wishlist) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *Wishlist) GetItems() []*WishlistItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateWishlistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateWishlistRequest) Reset() {
	*x = CreateWishlistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWishlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWishlistRequest) ProtoMessage() {}

func (x *CreateWishlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWishlistRequest.ProtoReflect.Descriptor instead.
func (*CreateWishlistRequest) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWishlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateWishlistRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListWishlistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ListWishlistsRequest) Reset() {
	*x = ListWishlistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWishlistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWishlistsRequest) ProtoMessage() {}

func (x *ListWishlistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWishlistsRequest.ProtoReflect.Descriptor instead.
func (*ListWishlistsRequest) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{4}
}

func (x *ListWishlistsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListWishlistsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wishlists []*Wishlist `protobuf:"bytes,1,rep,name=wishlists,proto3" json:"wishlists,omitempty"`
}

func (x *ListWishlistsResponse) Reset() {
	*x = ListWishlistsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWishlistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWishlistsResponse) ProtoMessage() {}

func (x *ListWishlistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWishlistsResponse.ProtoReflect.Descriptor instead.
func (*ListWishlistsResponse) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{5}
}

func (x *ListWishlistsResponse) GetWishlists() []*Wishlist {
	if x != nil {
		return x.Wishlists
	}
	return nil
}

type GetWishlistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetWishlistRequest) Reset() {
	*x = GetWishlistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWishlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWishlistRequest) ProtoMessage() {}

func (x *GetWishlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWishlistRequest.ProtoReflect.Descriptor instead.
func (*GetWishlistRequest) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{6}
}

func (x *GetWishlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetWishlistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RenameWishlistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RenameWishlistRequest) Reset() {
	*x = RenameWishlistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameWishlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameWishlistRequest) ProtoMessage() {}

func (x *RenameWishlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameWishlistRequest.ProtoReflect.Descriptor instead.
func (*RenameWishlistRequest) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{7}
}

func (x *RenameWishlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RenameWishlistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenameWishlistRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteWishlistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteWishlistRequest) Reset() {
	*x = DeleteWishlistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWishlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWishlistRequest) ProtoMessage() {}

func (x *DeleteWishlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWishlistRequest.ProtoReflect.Descriptor instead.
func (*DeleteWishlistRequest) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteWishlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteWishlistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddWishlistItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ProductId string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (x *AddWishlistItemRequest) Reset() {
	*x = AddWishlistItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddWishlistItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWishlistItemRequest) ProtoMessage() {}

func (x *AddWishlistItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWishlistItemRequest.ProtoReflect.Descriptor instead.
func (*AddWishlistItemRequest) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{9}
}

func (x *AddWishlistItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddWishlistItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddWishlistItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type RemoveWishlistItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ProductId string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (x *RemoveWishlistItemRequest) Reset() {
	*x = RemoveWishlistItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveWishlistItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWishlistItemRequest) ProtoMessage() {}

func (x *RemoveWishlistItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWishlistItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveWishlistItemRequest) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveWishlistItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveWishlistItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveWishlistItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type WishlistSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *WishlistSummaryRequest) Reset() {
	*x = WishlistSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WishlistSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishlistSummaryRequest) ProtoMessage() {}

func (x *WishlistSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishlistSummaryRequest.ProtoReflect.Descriptor instead.
func (*WishlistSummaryRequest) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{11}
}

func (x *WishlistSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WishlistSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListCount int32 `protobuf:"varint,1,opt,name=list_count,json=listCount,proto3" json:"list_count,omitempty"`
	ItemCount int32 `protobuf:"varint,2,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
}

func (x *WishlistSummaryResponse) Reset() {
	*x = WishlistSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WishlistSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishlistSummaryResponse) ProtoMessage() {}

func (x *WishlistSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishlistSummaryResponse.ProtoReflect.Descriptor instead.
func (*WishlistSummaryResponse) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{12}
}

func (x *WishlistSummaryResponse) GetListCount() int32 {
	if x != nil {
		return x.ListCount
	}
	return 0
}

func (x *WishlistSummaryResponse) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

var File_wishlist_proto protoreflect.FileDescriptor

var file_wishlist_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x68, 0x69, 0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x22, 0x0f, 0x0a,
	0x0d, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x48,
	0x0a, 0x0c, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x64, 0x64, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x65, 0x64, 0x41, 0x74, 0x22, 0x9d, 0x01, 0x0a, 0x08, 0x57, 0x69, 0x73,
	0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x74, 0x65, 0x6d,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x74,
	0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x68, 0x69, 0x70, 0x73, 0x74, 0x65, 0x72,
	0x73, 0x68, 0x6f, 0x70, 0x2e, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x44, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2f,
	0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x4c, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x77, 0x69, 0x73, 0x68,
	0x6c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68, 0x69,
	0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69,
	0x73, 0x74, 0x52, 0x09, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x22, 0x3d, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x54, 0x0a, 0x15,
	0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x40, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x60, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x57, 0x69, 0x73, 0x68, 0x6c,
	0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x19, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x16, 0x57,
	0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x57,
	0x0a, 0x17, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x73,
	0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c,
	0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x74, 0x65, 0x6d,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x74,
	0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xbb, 0x05, 0x0a, 0x0f, 0x57, 0x69, 0x73, 0x68,
	0x6c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x2e,
	0x68, 0x69, 0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x68, 0x69, 0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2e,
	0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0d, 0x4c, 0x69,
	0x73, 0x74, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x12, 0x21, 0x2e, 0x68, 0x69,
	0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69,
	0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x68, 0x69, 0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x57, 0x69, 0x73, 0x68, 0x6c,
	0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x68, 0x69, 0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x6f,
	0x70, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x68, 0x69, 0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68,
	0x6f, 0x70, 0x2e, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x4d, 0x0a,
	0x0e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x12,
	0x22, 0x2e, 0x68, 0x69, 0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x52, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x68, 0x69, 0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x6f,
	0x70, 0x2e, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x22,
	0x2e, 0x68, 0x69, 0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x68, 0x69, 0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70,
	0x2e, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x54, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x23, 0x2e, 0x68, 0x69, 0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x6f,
	0x70, 0x2e, 0x41, 0x64, 0x64, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x68, 0x69, 0x70, 0x73, 0x74,
	0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x26, 0x2e, 0x68,
	0x69, 0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x68, 0x69, 0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68,
	0x6f, 0x70, 0x2e, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x61, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73,
	0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x23, 0x2e, 0x68, 0x69, 0x70, 0x73, 0x74,
	0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x68, 0x69, 0x70, 0x73, 0x74, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x57, 0x69, 0x73, 0x68,
	0x6c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x50,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x68, 0x69, 0x70, 0x73, 0x74,
	0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wishlist_proto_rawDescOnce sync.Once
	file_wishlist_proto_rawDescData = file_wishlist_proto_rawDesc
)

func file_wishlist_proto_rawDescGZIP() []byte {
	file_wishlist_proto_rawDescOnce.Do(func() {
		file_wishlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_wishlist_proto_rawDescData)
	})
	return file_wishlist_proto_rawDescData
}

var file_wishlist_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_wishlist_proto_goTypes = []any{
	(*WishlistEmpty)(nil),             // 0: hipstershop.WishlistEmpty
	(*WishlistItem)(nil),              // 1: hipstershop.WishlistItem
	(*Wishlist)(nil),                  // 2: hipstershop.Wishlist
	(*CreateWishlistRequest)(nil),     // 3: hipstershop.CreateWishlistRequest
	(*ListWishlistsRequest)(nil),      // 4: hipstershop.ListWishlistsRequest
	(*ListWishlistsResponse)(nil),     // 5: hipstershop.ListWishlistsResponse
	(*GetWishlistRequest)(nil),        // 6: hipstershop.GetWishlistRequest
	(*RenameWishlistRequest)(nil),     // 7: hipstershop.RenameWishlistRequest
	(*DeleteWishlistRequest)(nil),     // 8: hipstershop.DeleteWishlistRequest
	(*AddWishlistItemRequest)(nil),    // 9: hipstershop.AddWishlistItemRequest
	(*RemoveWishlistItemRequest)(nil), // 10: hipstershop.RemoveWishlistItemRequest
	(*WishlistSummaryRequest)(nil),    // 11: hipstershop.WishlistSummaryRequest
	(*WishlistSummaryResponse)(nil),   // 12: hipstershop.WishlistSummaryResponse
}
var file_wishlist_proto_depIdxs = []int32{
	1,  // 0: hipstershop.Wishlist.items:type_name -> hipstershop.WishlistItem
	2,  // 1: hipstershop.ListWishlistsResponse.wishlists:type_name -> hipstershop.Wishlist
	3,  // 2: hipstershop.WishlistService.CreateWishlist:input_type -> hipstershop.CreateWishlistRequest
	4,  // 3: hipstershop.WishlistService.ListWishlists:input_type -> hipstershop.ListWishlistsRequest
	6,  // 4: hipstershop.WishlistService.GetWishlist:input_type -> hipstershop.GetWishlistRequest
	7,  // 5: hipstershop.WishlistService.RenameWishlist:input_type -> hipstershop.RenameWishlistRequest
	8,  // 6: hipstershop.WishlistService.DeleteWishlist:input_type -> hipstershop.DeleteWishlistRequest
	9,  // 7: hipstershop.WishlistService.AddWishlistItem:input_type -> hipstershop.AddWishlistItemRequest
	10, // 8: hipstershop.WishlistService.RemoveWishlistItem:input_type -> hipstershop.RemoveWishlistItemRequest
	11, // 9: hipstershop.WishlistService.GetWishlistSummary:input_type -> hipstershop.WishlistSummaryRequest
	2,  // 10: hipstershop.WishlistService.CreateWishlist:output_type -> hipstershop.Wishlist
	5,  // 11: hipstershop.WishlistService.ListWishlists:output_type -> hipstershop.ListWishlistsResponse
	2,  // 12: hipstershop.WishlistService.GetWishlist:output_type -> hipstershop.Wishlist
	2,  // 13: hipstershop.WishlistService.RenameWishlist:output_type -> hipstershop.Wishlist
	0,  // 14: hipstershop.WishlistService.DeleteWishlist:output_type -> hipstershop.WishlistEmpty
	0,  // 15: hipstershop.WishlistService.AddWishlistItem:output_type -> hipstershop.WishlistEmpty
	0,  // 16: hipstershop.WishlistService.RemoveWishlistItem:output_type -> hipstershop.WishlistEmpty
	12, // 17: hipstershop.WishlistService.GetWishlistSummary:output_type -> hipstershop.WishlistSummaryResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_wishlist_proto_init() }
func file_wishlist_proto_init() {
	if File_wishlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wishlist_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WishlistEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WishlistItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Wishlist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateWishlistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ListWishlistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListWishlistsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetWishlistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RenameWishlistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteWishlistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*AddWishlistItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveWishlistItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*WishlistSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*WishlistSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wishlist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wishlist_proto_goTypes,
		DependencyIndexes: file_wishlist_proto_depIdxs,
		MessageInfos:      file_wishlist_proto_msgTypes,
	}.Build()
	File_wishlist_proto = out.File
	file_wishlist_proto_rawDesc = nil
	file_wishlist_proto_goTypes = nil
	file_wishlist_proto_depIdxs = nil
}
