// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: wishlist.proto

package hipstershop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WishlistService_CreateWishlist_FullMethodName     = "/hipstershop.WishlistService/CreateWishlist"
	WishlistService_ListWishlists_FullMethodName      = "/hipstershop.WishlistService/ListWishlists"
	WishlistService_GetWishlist_FullMethodName        = "/hipstershop.WishlistService/GetWishlist"
	WishlistService_RenameWishlist_FullMethodName     = "/hipstershop.WishlistService/RenameWishlist"
	WishlistService_DeleteWishlist_FullMethodName     = "/hipstershop.WishlistService/DeleteWishlist"
	WishlistService_AddWishlistItem_FullMethodName    = "/hipstershop.WishlistService/AddWishlistItem"
	WishlistService_RemoveWishlistItem_FullMethodName = "/hipstershop.WishlistService/RemoveWishlistItem"
	WishlistService_GetWishlistSummary_FullMethodName = "/hipstershop.WishlistService/GetWishlistSummary"
)

// WishlistServiceClient is the client API for WishlistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WishlistServiceClient interface {
	CreateWishlist(ctx context.Context, in *CreateWishlistRequest, opts ...grpc.CallOption) (*Wishlist, error)
	ListWishlists(ctx context.Context, in *ListWishlistsRequest, opts ...grpc.CallOption) (*ListWishlistsResponse, error)
	GetWishlist(ctx context.Context, in *GetWishlistRequest, opts ...grpc.CallOption) (*Wishlist, error)
	RenameWishlist(ctx context.Context, in *RenameWishlistRequest, opts ...grpc.CallOption) (*Wishlist, error)
	DeleteWishlist(ctx context.Context, in *DeleteWishlistRequest, opts ...grpc.CallOption) (*WishlistEmpty, error)
	AddWishlistItem(ctx context.Context, in *AddWishlistItemRequest, opts ...grpc.CallOption) (*WishlistEmpty, error)
	RemoveWishlistItem(ctx context.Context, in *RemoveWishlistItemRequest, opts ...grpc.CallOption) (*WishlistEmpty, error)
	GetWishlistSummary(ctx context.Context, in *WishlistSummaryRequest, opts ...grpc.CallOption) (*WishlistSummaryResponse, error)
}

type wishlistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWishlistServiceClient(cc grpc.ClientConnInterface) WishlistServiceClient {
	return &wishlistServiceClient{cc}
}

func (c *wishlistServiceClient) CreateWishlist(ctx context.Context, in *CreateWishlistRequest, opts ...grpc.CallOption) (*Wishlist, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Wishlist)
	err := c.cc.Invoke(ctx, WishlistService_CreateWishlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) ListWishlists(ctx context.Context, in *ListWishlistsRequest, opts ...grpc.CallOption) (*ListWishlistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWishlistsResponse)
	err := c.cc.Invoke(ctx, WishlistService_ListWishlists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) GetWishlist(ctx context.Context, in *GetWishlistRequest, opts ...grpc.CallOption) (*Wishlist, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Wishlist)
	err := c.cc.Invoke(ctx, WishlistService_GetWishlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) RenameWishlist(ctx context.Context, in *RenameWishlistRequest, opts ...grpc.CallOption) (*Wishlist, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Wishlist)
	err := c.cc.Invoke(ctx, WishlistService_RenameWishlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) DeleteWishlist(ctx context.Context, in *DeleteWishlistRequest, opts ...grpc.CallOption) (*WishlistEmpty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishlistEmpty)
	err := c.cc.Invoke(ctx, WishlistService_DeleteWishlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) AddWishlistItem(ctx context.Context, in *AddWishlistItemRequest, opts ...grpc.CallOption) (*WishlistEmpty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishlistEmpty)
	err := c.cc.Invoke(ctx, WishlistService_AddWishlistItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) RemoveWishlistItem(ctx context.Context, in *RemoveWishlistItemRequest, opts ...grpc.CallOption) (*WishlistEmpty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishlistEmpty)
	err := c.cc.Invoke(ctx, WishlistService_RemoveWishlistItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistServiceClient) GetWishlistSummary(ctx context.Context, in *WishlistSummaryRequest, opts ...grpc.CallOption) (*WishlistSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishlistSummaryResponse)
	err := c.cc.Invoke(ctx, WishlistService_GetWishlistSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WishlistServiceServer is the server API for WishlistService service.
// All implementations must embed UnimplementedWishlistServiceServer
// for forward compatibility.
type WishlistServiceServer interface {
	CreateWishlist(context.Context, *CreateWishlistRequest) (*Wishlist, error)
	ListWishlists(context.Context, *ListWishlistsRequest) (*ListWishlistsResponse, error)
	GetWishlist(context.Context, *GetWishlistRequest) (*Wishlist, error)
	RenameWishlist(context.Context, *RenameWishlistRequest) (*Wishlist, error)
	DeleteWishlist(context.Context, *DeleteWishlistRequest) (*WishlistEmpty, error)
	AddWishlistItem(context.Context, *AddWishlistItemRequest) (*WishlistEmpty, error)
	RemoveWishlistItem(context.Context, *RemoveWishlistItemRequest) (*WishlistEmpty, error)
	GetWishlistSummary(context.Context, *WishlistSummaryRequest) (*WishlistSummaryResponse, error)
	mustEmbedUnimplementedWishlistServiceServer()
}

// UnimplementedWishlistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWishlistServiceServer struct{}

func (UnimplementedWishlistServiceServer) CreateWishlist(context.Context, *CreateWishlistRequest) (*Wishlist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWishlist not implemented")
}
func (UnimplementedWishlistServiceServer) ListWishlists(context.Context, *ListWishlistsRequest) (*ListWishlistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWishlists not implemented")
}
func (UnimplementedWishlistServiceServer) GetWishlist(context.Context, *GetWishlistRequest) (*Wishlist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWishlist not implemented")
}
func (UnimplementedWishlistServiceServer) RenameWishlist(context.Context, *RenameWishlistRequest) (*Wishlist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameWishlist not implemented")
}
func (UnimplementedWishlistServiceServer) DeleteWishlist(context.Context, *DeleteWishlistRequest) (*WishlistEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWishlist not implemented")
}
func (UnimplementedWishlistServiceServer) AddWishlistItem(context.Context, *AddWishlistItemRequest) (*WishlistEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWishlistItem not implemented")
}
func (UnimplementedWishlistServiceServer) RemoveWishlistItem(context.Context, *RemoveWishlistItemRequest) (*WishlistEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveWishlistItem not implemented")
}
func (UnimplementedWishlistServiceServer) GetWishlistSummary(context.Context, *WishlistSummaryRequest) (*WishlistSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWishlistSummary not implemented")
}
func (UnimplementedWishlistServiceServer) mustEmbedUnimplementedWishlistServiceServer() {}
func (UnimplementedWishlistServiceServer) testEmbeddedByValue()                         {}

// UnsafeWishlistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WishlistServiceServer will
// result in compilation errors.
type UnsafeWishlistServiceServer interface {
	mustEmbedUnimplementedWishlistServiceServer()
}

func RegisterWishlistServiceServer(s grpc.ServiceRegistrar, srv WishlistServiceServer) {
	// If the following call pancis, it indicates UnimplementedWishlistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WishlistService_ServiceDesc, srv)
}

func _WishlistService_CreateWishlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWishlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).CreateWishlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_CreateWishlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).CreateWishlist(ctx, req.(*CreateWishlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_ListWishlists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWishlistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).ListWishlists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_ListWishlists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).ListWishlists(ctx, req.(*ListWishlistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_GetWishlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWishlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).GetWishlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_GetWishlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).GetWishlist(ctx, req.(*GetWishlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_RenameWishlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameWishlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).RenameWishlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_RenameWishlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).RenameWishlist(ctx, req.(*RenameWishlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_DeleteWishlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWishlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).DeleteWishlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_DeleteWishlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).DeleteWishlist(ctx, req.(*DeleteWishlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_AddWishlistItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWishlistItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).AddWishlistItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_AddWishlistItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).AddWishlistItem(ctx, req.(*AddWishlistItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_RemoveWishlistItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWishlistItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).RemoveWishlistItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_RemoveWishlistItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).RemoveWishlistItem(ctx, req.(*RemoveWishlistItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistService_GetWishlistSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WishlistSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistServiceServer).GetWishlistSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistService_GetWishlistSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistServiceServer).GetWishlistSummary(ctx, req.(*WishlistSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WishlistService_ServiceDesc is the grpc.ServiceDesc for WishlistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WishlistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hipstershop.WishlistService",
	HandlerType: (*WishlistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWishlist",
			Handler:    _WishlistService_CreateWishlist_Handler,
		},
		{
			MethodName: "ListWishlists",
			Handler:    _WishlistService_ListWishlists_Handler,
		},
		{
			MethodName: "GetWishlist",
			Handler:    _WishlistService_GetWishlist_Handler,
		},
		{
			MethodName: "RenameWishlist",
			Handler:    _WishlistService_RenameWishlist_Handler,
		},
		{
			MethodName: "DeleteWishlist",
			Handler:    _WishlistService_DeleteWishlist_Handler,
		},
		{
			MethodName: "AddWishlistItem",
			Handler:    _WishlistService_AddWishlistItem_Handler,
		},
		{
			MethodName: "RemoveWishlistItem",
			Handler:    _WishlistService_RemoveWishlistItem_Handler,
		},
		{
			MethodName: "GetWishlistSummary",
			Handler:    _WishlistService_GetWishlistSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wishlist.proto",
}
